### ISSUE TITLE
中文文档 缺少 }

### ISSUE THREAD

**Issue by niexiaofei1988** [electron/i18n#1803]
[main.js](https://www.electronjs.org/docs/tutorial/quick-start#%E5%88%9B%E5%BB%BA%E4%B8%BB%E8%84%9A%E6%9C%AC%E6%96%87%E4%BB%B6)

<img width="1260" alt="未命名" src="https://user-images.githubusercontent.com/16014141/111869575-2ce49680-89bb-11eb-8a28-e0f683c0e02f.png">

**Comment by BodaThomas** [comment]
Need translations please

**Comment by AppleOfGray** [comment]
User niexiaofei1988 said that in chinese document (https://www.electronjs.org/docs/tutorial/quick-start), the left curly bracket is missing from the code. but the problem is not find in official website now(Has been fixed). this issue can be closed.

---

用户 niexiaofei1988 说中文文档内(https://www.electronjs.org/docs/tutorial/quick-start) 有一段代码缺少左侧花括号, 但现在这个问题在官网找不到了(已经被修复了), 当前issue可以被关闭了
